import 'package:medcases/services/clinical_catalog/clinical_catalog_platform.dart';
import 'dart:io';import 'dart:convert';import 'package:flutter_test/flutter_test.dart';import 'package:medcases/services/clinical_catalog/clinical_catalog_repository.dart';import 'package:medcases/services/clinical_catalog/clinical_catalog_functional_baseline.dart';import 'package:medcases/services/plantao_machine_native_context_prefetch.dart';import 'package:medcases/services/clinical_content/clinical_content_models.dart';import 'package:medcases/services/clinical_content/clinical_content_contract.dart';
Map<String,dynamic> load(String n)=>(jsonDecode(File('../$n').readAsStringSync()) as Map).cast<String,dynamic>();
Map<String,dynamic> envelope(Map<String,dynamic> r,String status){final m={...r['manifest'] as Map,'status':status};return {'pointer':{'activeVersion':m['contentVersion'],'schemaVersion':m['schemaVersion'],'manifestSha256':clinicalHash(m),'status':status},'manifest':m,'chunks':{for(final e in (r['chunks'] as Map).entries)e.key:e.value['json']}};}
class Remote implements ClinicalCatalogRemote{Remote(this.value);Map<String,dynamic> value;bool offline=false;Future<Map<String,dynamic>> pointer()async{if(offline)throw StateError('offline');return (value['pointer'] as Map).cast();}Future<Map<String,dynamic>> manifest(String version)async=>(value['manifest'] as Map).cast();Future<String> chunk(String version,String id)async=>value['chunks'][id] as String;}
class Cache implements ClinicalCatalogCache{Map<String,dynamic>? value;int writes=0;Future<Map<String,dynamic>?> read()async=>value;Future<void> write(Map<String,dynamic> v)async{value=jsonDecode(jsonEncode(v));writes++;}}
class EmptySource implements PlantaoMachineNativeRegistrySource{Future<List<Map<String,dynamic>>> loadEnabled(String c)async=>[];Future<List<Map<String,dynamic>>> loadPathology(String c,String k,{String fieldPath='canonicalPathologyKey'})async=>[];}
ClinicalCatalogRepository repo(Remote r,Cache c)=>ClinicalCatalogRepository(remote:r,cache:c,requiredSurfaceOwners:clinicalRequiredSurfaceOwners,pointerTtl:Duration.zero);
void main(){TestWidgetsFlutterBinding.ensureInitialized();final a=load('snapshot-A.json'),b=load('snapshot-B.json');
 test('A/B exact sets and partial mode availability',(){for(final release in [a,b]){final x=ClinicalCatalogValidator.validate(envelope(release,'ACTIVE'),ClinicalCatalogOrigin.remote);for(final e in clinicalRequiredSurfaceOwners.entries){final parts=e.key.split('_');expect(x.surfaceOwners(parts[0],parts[1]),containsAll(e.value));}}final x=ClinicalCatalogValidator.validate(envelope(b,'ACTIVE'),ClinicalCatalogOrigin.remote);final only=(b['manifest']['owners'] as List).firstWhere((m)=>m['availableModes']['study']['pt']==false)['ownerId'] as String;for(final l in ['pt','es']){expect(x.projections('study',l,owner:only),isEmpty);expect(x.context(only.replaceAll('_',' '),'study',l),'');expect(x.projections('plantao',l,owner:only),isNotEmpty);}expect((a['manifest']['owners'] as List).any((m)=>m['referenceState']['study']['pt']=='legacy_missing'),true);expect((a['manifest']['owners'] as List).any((m)=>m['referenceState']['study']['pt']=='legacy_locale_divergence'),true);});
 test('270 Study ProtocolModels retain every field and reference',(){final x=ClinicalCatalogValidator.validate(envelope(a,'ACTIVE'),ClinicalCatalogOrigin.remote);final originals=jsonDecode(File('../full-legacy-protocols.json').readAsStringSync()) as List;expect(x.legacyProtocolPayloads.length,originals.length);for(final original in originals){final raw=x.legacyProtocolPayloads.singleWhere((p)=>p['id']==original['id']);expect(raw,original['fields']);final model=ClinicalContentModels.protocol(ClinicalContentItem({'canonicalId':raw['id'],'payload':raw}));expect(ClinicalContentModels.protocolPayload(model),raw);}});
 test('307 inherited Plantao contexts and supplemental routing remain identical in PT/ES',()async{final repository=repo(Remote(envelope(b,'ACTIVE')),Cache());final x=await repository.acquire();expect(x.isBundled,false);final expected=jsonDecode(File('../../remote-content-migration-r5-2026-10-06/runtime-contexts.json').readAsStringSync()) as List;final prefetch=PlantaoMachineNativeContextPrefetch(repository:repository,legacyFallbackSource:EmptySource());var checked=0;for(final m in b['manifest']['owners'] as List){if(m['routeKind']!='legacy_source_context')continue;final owner=m['ownerId'] as String;for(final l in ['pt','es']){final result=await prefetch.prefetchAttested(userText:owner.replaceAll('_',' '),language:l,supplementalEvidence:(e)async=>'EXISTING_SUPPLEMENTAL_ROUTE');final original=expected.singleWhere((e)=>e['ownerId']==owner);expect(result.result.canonicalPathologyKey,owner);expect(result.result.providerPromptBlock,original['locales'][l]['providerPrompt']);expect(result.providerInput,endsWith('EXISTING_SUPPLEMENTAL_ROUTE'));expect(result.attestation.catalogSnapshot!.version,b['manifest']['contentVersion']);checked++;}}expect(checked,614);},timeout:const Timeout(Duration(minutes:3)));
 test('DRAFT, offline restart, cache failover and pointer rollback preserve valid leases',()async{final c=Cache(),r=Remote(envelope(a,'DRAFT'));expect((await repo(r,c).acquire()).isBundled,true);expect(c.writes,0);r.value=envelope(a,'ACTIVE');final repository=repo(r,c);final leaseA=await repository.acquire();expect(leaseA.isBundled,false);r.offline=true;expect((await repo(r,c).acquire()).origin,ClinicalCatalogOrigin.cache);expect((await repo(r,Cache()).acquire()).isBundled,true);r.offline=false;r.value=envelope(b,'ACTIVE');final leaseB=await repository.acquire(refresh:true);expect(leaseB.version,b['manifest']['contentVersion']);final before=jsonEncode(c.value),bad=envelope(b,'ACTIVE');bad['chunks'][(bad['chunks'] as Map).keys.first]+=' ';r.value=bad;expect((await repository.acquire(refresh:true)).version,leaseB.version);expect(jsonEncode(c.value),before);r.value=envelope(a,'ACTIVE');expect((await repository.acquire(refresh:true)).version,leaseA.version);expect(leaseB.version,b['manifest']['contentVersion']);},timeout:const Timeout(Duration(minutes:3)));
 test('Invalid manifest surface count rejects snapshot',(){final bad=envelope(a,'ACTIVE');bad['manifest']['studyPtCount']=0;bad['pointer']['manifestSha256']=clinicalHash(bad['manifest']);expect(()=>ClinicalCatalogValidator.validate(bad,ClinicalCatalogOrigin.remote),throwsA(isA<ClinicalCatalogInvalid>()));});
 test('Self-consistent partial snapshot cannot displace valid cache',()async{final c=Cache(),r=Remote(envelope(a,'ACTIVE'));final repository=repo(r,c);final valid=await repository.acquire();final previous=jsonEncode(c.value);final partial=envelope(load('snapshot-partial.json'),'ACTIVE');expect(ClinicalCatalogValidator.validate(partial,ClinicalCatalogOrigin.remote).rows('clinical_identity_registry').length,576);r.value=partial;expect((await repository.acquire(refresh:true)).version,valid.version);expect(jsonEncode(c.value),previous);r.offline=true;expect((await repo(r,c).acquire()).version,valid.version);},timeout:const Timeout(Duration(minutes:3)));
 test('577 baseline Plantao contexts and supplemental routing remain identical in PT/ES',()async{final repository=repo(Remote(envelope(a,'ACTIVE')),Cache());final x=await repository.acquire();expect(x.isBundled,false);final expected=jsonDecode(File('../../remote-content-migration-r5-2026-10-06/runtime-contexts.json').readAsStringSync()) as List;final prefetch=PlantaoMachineNativeContextPrefetch(repository:repository,legacyFallbackSource:EmptySource());var checked=0;for(final m in a['manifest']['owners'] as List){if(m['routeKind']!='legacy_source_context')continue;final owner=m['ownerId'] as String;for(final l in ['pt','es']){final result=await prefetch.prefetchAttested(userText:owner.replaceAll('_',' '),language:l,supplementalEvidence:(e)async=>'EXISTING_SUPPLEMENTAL_ROUTE');final original=expected.singleWhere((e)=>e['ownerId']==owner);expect(result.result.canonicalPathologyKey,owner);expect(result.result.providerPromptBlock,original['locales'][l]['providerPrompt']);expect(result.providerInput,endsWith('EXISTING_SUPPLEMENTAL_ROUTE'));expect(result.attestation.catalogSnapshot!.version,a['manifest']['contentVersion']);checked++;}}expect(checked,1154);},timeout:const Timeout(Duration(minutes:3)));
 test('Physical file cache survives repository restart and partial snapshot',()async{final dir=await Directory.systemTemp.createTemp('medcases-r6-cache-');try{final r=Remote(envelope(a,'ACTIVE'));ClinicalCatalogRepository open()=>ClinicalCatalogRepository(remote:r,cache:FileClinicalCatalogCache(directory:dir),requiredSurfaceOwners:clinicalRequiredSurfaceOwners,pointerTtl:Duration.zero);final first=await open().acquire();expect(first.isBundled,false);final file=File('${dir.path}/clinical_catalog_r2/last_valid.json');final before=await file.readAsString();r.offline=true;expect((await open().acquire()).origin,ClinicalCatalogOrigin.cache);r.offline=false;r.value=envelope(load('snapshot-partial.json'),'ACTIVE');expect((await open().acquire(refresh:true)).version,first.version);expect(await file.readAsString(),before);expect(await File('${file.path}.pending').exists(),false);}finally{await dir.delete(recursive:true);}},timeout:const Timeout(Duration(minutes:3)));

}
