'use strict';
const {SECTION_LABELS} = require('./plantao_clinical_snapshot');
const object = properties => ({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const str = pattern => ({type:'string',...(pattern?{pattern}:{})});
const id = str('^[a-z][a-z0-9_]{0,79}$');
const code = str('^[a-z0-9][a-z0-9_≤≥<>=%.-]{0,99}$');
const labels = object({pt:str('^[^\\r\\n{}]+$'),es:str('^[^\\r\\n{}]+$')});
// A number cannot be regenerated by the localization branch. All numeric
// content (including thresholds/counts) is bound to a shared quantity slot.
const clinicalLabels = object({pt:str('^[^\\r\\n{}0-9]+$'),es:str('^[^\\r\\n{}0-9]+$')});
const quantityUnits = '(?:mcg|mg|kg|mL|ml|mmol|mEq|meq|mol|mosm|mmHg|mmhg|bpm|cm|mm|min|VO|PO|IV|EV|IM|SC|IO|UI|IU|vo|po|iv|ev|im|sc|io|ui|iu|µg|μg|g|L|l|h|s|d|m|x|U|u)\\b';
const quantityPattern = '^[+−–<>≤≥=\\s-]*[0-9]+(?:[0-9.,+−–<>≤≥=%²\\s/()*-]|'+quantityUnits+'|q[0-9]+(?:h|min|d|s)\\b)*$';
const templatePattern = '^(?:[ \\t.,;:()!?–—/\\*+=<>≤≥%×→-]|\\{\\{[a-z][a-z0-9_]{0,79}\\}\\})+$';
const quantityToken = {anyOf:[
  object({kind:{type:'string',enum:['number']},value:str('^-?[0-9]+(?:[.,][0-9]+)?$')}),
  object({kind:{type:'string',enum:['unit']},value:{type:'string',enum:['mg','mcg','g','kg','mL','L','mmol','mEq','mmHg','bpm','cm','m²','h','min','s','d','VO','IV','IM','SC','IO','UI']}}),
  object({kind:{type:'string',enum:['operator']},value:{type:'string',enum:['/','–','<','>','≤','≥','q','x','%','(',')','+']}}),
]};
const slot = {anyOf:[
  object({id,kind:{type:'string',enum:['quantity']},value:{type:'array',items:quantityToken,minItems:1}}),
  object({id,kind:{type:'string',enum:['clinical_concept','condition','relation']},value:code,labels:clinicalLabels}),
]};
const fact = object({id,action:{type:'string',enum:['assess','treat','monitor','avoid','consider','explain','refer']},
  polarity:{type:'string',enum:['affirmative','negative','conditional']},
  conceptCodes:{type:'array',items:code,minItems:1},conditionCodes:{type:'array',items:code},
  slots:{type:'array',items:slot,minItems:1}});

function snapshotSchema(sources=[]) {
  return object({records:{type:'array',minItems:2,items:{anyOf:[
    object({type:{type:'string',enum:['title']},id,labels}),
    // Bounded output tokens and the density contract own response size.
    // Gemini rejects maxItems on this nested union; it is not a safety rule.
    object({type:{type:'string',enum:['section']},id:{type:'string',enum:Object.keys(SECTION_LABELS)},facts:{type:'array',items:fact,minItems:1}}),
    // With no verified sources, no references record is valid or needed.
    ...(sources.length ? [object({type:{type:'string',enum:['references']},sourceIds:{type:'array',items:{type:'string',enum:sources.map(s=>s.id)}}})] : []),
  ]}}});
}
module.exports={snapshotSchema,quantityPattern,templatePattern};
