'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createAdminControlCenter,project}=require('../admin_control_center');
// Transaction double serializes commits and discards staged writes on failure.
function database(){const data=new Map();let pending=Promise.resolve();const ref=(c,id)=>({id,key:c+'/'+id,get:async()=>snap(c,id)});const snap=(c,id)=>({id,exists:data.has(c+'/'+id),data:()=>structuredClone(data.get(c+'/'+id))});const db={data,collection:c=>({doc:id=>ref(c,id),where(f,op,v){const filters=[[f,op,v]];return {where(f,op,v){filters.push([f,op,v]);return this;},limit(n){this.n=n;return this;},async get(){return {docs:[...data.keys()].filter(k=>k.startsWith(c+'/')&&filters.every(([f,op,v])=>op==='in'?v.includes(data.get(k)[f]):data.get(k)[f]===v)).slice(0,this.n).map(k=>snap(c,k.slice(c.length+1)))};}};}}),runTransaction:fn=>{const work=pending.then(async()=>{const writes=[];const tx={get:r=>r.get(),create:(r,v)=>{assert(!data.has(r.key));writes.push([r.key,v]);},update:(r,v)=>writes.push([r.key,{...data.get(r.key),...v}])};const result=await fn(tx);for(const [k,v] of writes)data.set(k,v);return result;});pending=work.catch(()=>{});return work;}};for(const [uid,role] of [['master','master'],['admin','admin'],['supervisor','supervisor'],['normal','user'],['target','user']])data.set('users/'+uid,{role,status:'approved'});return db;}
for(const role of ['master','admin','supervisor'])test(role+' read authorization',async()=>{const r=createAdminControlCenter({db:database()});assert.equal(await r.authorize(role),role);});
for(const role of ['normal',null,'missing'])test(String(role)+' denied',async()=>{await assert.rejects(createAdminControlCenter({db:database()}).authorize(role));});
test('supervisor server write denied',async()=>{await assert.rejects(createAdminControlCenter({db:database()}).mutate('supervisor',{}),/SUPERVISOR_READ_ONLY/);});
test('blocked admin denied even with role',async()=>{const db=database();db.data.set('users/admin',{role:'admin',status:'blocked'});await assert.rejects(createAdminControlCenter({db}).authorize('admin'),/ADMIN_ACCESS_DENIED/);});
const grant={action:'grantCredit',requestId:'request-1',userId:'target',amountSeconds:3600,category:'SUPORTE',reason:'Synthetic support adjustment'};
for(const actor of ['admin','master'])test(actor+' grant + concurrent retries: one ledger one audit, base untouched',async()=>{const db=database(),r=createAdminControlCenter({db,now:()=>100});const before=structuredClone(db.data.get('users/target'));const all=await Promise.all(Array.from({length:10},()=>r.mutate(actor,grant)));assert(all.every(x=>x.creditId===all[0].creditId));assert.equal([...db.data.keys()].filter(x=>x.startsWith('adminCreditLedger/')).length,1);assert.equal([...db.data.keys()].filter(x=>x.startsWith('adminControlAudit/')).length,1);assert.deepEqual(db.data.get('users/target'),before);});
test('retry different payload rejected',async()=>{const r=createAdminControlCenter({db:database(),now:()=>100});await r.mutate('admin',grant);await assert.rejects(r.mutate('admin',{...grant,amountSeconds:3601}),/IDEMPOTENCY_CONFLICT/);});
test('revoke only unused; reserved/history preserved',async()=>{const db=database(),r=createAdminControlCenter({db,now:()=>100});const {creditId}=await r.mutate('admin',grant);const c=db.data.get('adminManualCredits/'+creditId);c.remainingSeconds=3000;c.reservedSeconds=100;const result=await r.mutate('admin',{action:'revokeCredit',requestId:'request-2',creditId,reason:'Synthetic revocation'});assert.equal(result.revokedSeconds,2900);assert.equal(db.data.get('adminManualCredits/'+creditId).remainingSeconds,100);assert.equal([...db.data.keys()].filter(x=>x.startsWith('adminCreditLedger/')).length,2);});
test('invalid credit rejected without writes',async()=>{for(const amount of [-1,0,Infinity,1.5,31536001]){const db=database();await assert.rejects(createAdminControlCenter({db}).mutate('admin',{...grant,amountSeconds:amount}));assert.equal(db.data.size,5);}});
test('expired grant rejected',async()=>{await assert.rejects(createAdminControlCenter({db:database(),now:()=>100}).mutate('admin',{...grant,expiresAt:99}),/INVALID_EXPIRY/);});
test('projection omits token, PHI, nested values',()=>{const row=project({id:'x',data:()=>({state:'done',transcript:'secret',token:'secret',provider:{key:'secret'}})},['state','provider']);assert.deepEqual(row,{id:'x',state:'done',provider:null});});
test('role checked again inside transaction',async()=>{const db=database();const run=db.runTransaction;db.runTransaction=fn=>{db.data.set('users/admin',{role:'user'});return run(fn);};await assert.rejects(createAdminControlCenter({db}).mutate('admin',grant),/ADMIN_ACCESS_DENIED/);assert.equal(db.data.size,5);});

test('deployed callable exposes only manual time scope',async()=>{
 const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
 const source=fs.readFileSync(path.join(__dirname,'../admin_control_exports.js'),'utf8');
 const box={module:{exports:{}},require:name=>name.endsWith('/https')?{onCall:(_,fn)=>fn,HttpsError:class extends Error{constructor(code,message){super(message);this.code=code;}}}:name.endsWith('/scheduler')?{onSchedule:(_,fn)=>fn}:{createAdminControlCenter:()=>{throw Error('RUNTIME_SHOULD_NOT_START');}},console};
 vm.runInNewContext(source,box);const handler=box.module.exports({}).adminControlCenter;
 for(const data of [{operation:'dashboard'},{operation:'list',payload:{table:'users'}},{operation:'mutate',payload:{action:'setIncidentState'}}])await assert.rejects(handler({auth:{uid:'admin'},data}),/UNKNOWN_OPERATION|OUTSIDE_MANUAL_TIME_SCOPE/);
 await assert.rejects(handler({data:{operation:'list',payload:{table:'credits'}}}),/UNAUTHENTICATED/);
});
