"use strict";
const assert=require("assert"); const fs=require("fs");
const {ClinicalManagementDependencyResolver}=require("../clinical_context/clinical_management_dependency_resolver");
const m46=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative18.phase19.local.json","utf8"));
const m47=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative75.phase20.local.json","utf8"));
const evidence=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_management_authoring_evidence.authoritative75.phase20.local.json","utf8"));
const supplement=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_registry_machine_native_supplement.phase20_management270_authoritative75.local.json","utf8"));
const report=JSON.parse(fs.readFileSync("functions/clinical_context/generated/global_clinical_context_superbuild47_management_next57_report.local.json","utf8"));
assert.strictEqual(m47.recordCount,270); assert.strictEqual(m47.enabledCount,75); assert.strictEqual(m47.managementReadyCount,75); assert.strictEqual(m47.failClosedCount,195); assert.strictEqual(m47.visibleCutoverEligibleCount,0);
assert.strictEqual(m47.newAuthoritativeKeys.length,57); assert.strictEqual(new Set(m47.newAuthoritativeKeys).size,57); assert.strictEqual(m47.selectedAuthoritativeKeys.length,75);
assert.strictEqual(new Set(m47.records.map(r=>r.protocolKey)).size,270); assert.strictEqual(new Set(m47.records.map(r=>r.canonicalPathologyKey)).size,270); assert.strictEqual(new Set(m47.records.map(r=>r.managementRuleKey)).size,270);
const by46=new Map(m46.records.map(r=>[r.canonicalPathologyKey,r])); const by47=new Map(m47.records.map(r=>[r.canonicalPathologyKey,r]));
for(const k of m46.selectedAuthoritativeKeys){assert.deepStrictEqual(by47.get(k),by46.get(k),`M46 enabled record drift:${k}`);}
const enabled=m47.records.filter(r=>r.enabled===true); const disabled=m47.records.filter(r=>r.enabled===false); assert.strictEqual(enabled.length,75); assert.strictEqual(disabled.length,195);
for(const r of enabled){assert.strictEqual(r.managementReady,true); assert.strictEqual(r.visibleCutoverEligible,false); assert.strictEqual(r.legacyManagementPromotedAutomatically,false); assert.strictEqual(r.managementInferredFromClassificationName,false); assert.strictEqual(r.clinicalSemanticInferencePerformed,false); assert(Array.isArray(r.provenance)&&r.provenance.length>0); for(const p of r.provenance){assert(/^https:\/\//.test(String(p.url||""))); assert.strictEqual(p.managementAuthorityValidated,true); assert.strictEqual(p.automaticPromotion,false);} for(const f of ["initialActions","definitiveActions","conditionalActions","contraindicatedActions","monitoring","reassessment","escalationCriteria"]){assert(Array.isArray(r[f])); for(const a of r[f]){assert(String(a.pt||"").trim()); assert(String(a.es||"").trim());}}}
assert.strictEqual(evidence.recordCount,270); assert.strictEqual(evidence.previousAuthoritativeCount,18); assert.strictEqual(evidence.newAuthoritativeAuthoredCount,57); assert.strictEqual(evidence.cumulativeAuthoritativeCount,75); assert.strictEqual(evidence.inheritedFailClosedCount,195);
assert.strictEqual(supplement.managementRules.length,270); assert.strictEqual(supplement.classifications.length,0); assert.strictEqual(supplement.actions.length,0); assert.strictEqual(supplement.content.length,0); assert.strictEqual(supplement.cloudWriteAuthorized,false); assert.strictEqual(supplement.backendDeployAuthorized,false); assert.strictEqual(supplement.remoteConfigWriteAuthorized,false); assert.strictEqual(supplement.shadowS1Percent,1); assert.strictEqual(supplement.shadowPercentChangeAuthorized,false); assert.strictEqual(supplement.visibleCutover,false);
assert.strictEqual(report.authoritativeCurrentEnabled,75); assert.strictEqual(report.retainedFailClosed,195); assert.strictEqual(report.shadowS1Percent,1); assert.strictEqual(report.visibleCutover,false); assert.strictEqual(report.cloudMutation,false);
const resolver=new ClinicalManagementDependencyResolver(); let rule=by47.get("bradiarritmia_grave"); let result=resolver.resolve({pathologyKey:rule.canonicalPathologyKey,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,true); assert.strictEqual(result.managementRuleKey,rule.managementRuleKey); assert.strictEqual(result.payload.authoringPolicy,"AUTHORITATIVE_CURRENT_OR_FAIL_CLOSED");
rule=disabled[0]; result=resolver.resolve({pathologyKey:rule.canonicalPathologyKey,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,false); assert.strictEqual(result.reason,"management_rule_not_registered");
const flat=k=>JSON.stringify(by47.get(k)).toLowerCase(); assert(flat("hda_varizeal").includes("12 h")); assert(flat("hemorragia_digestiva_baixa").includes("angio-tc")); assert(flat("hiponatremia_grave").includes("3%")); assert(flat("priapismo_emergencia").includes("fenilefrina")); assert(flat("politrauma_atls").includes("xabcde"));
console.log("SUPERBUILD47_CONTRACT=PASS"); console.log("SUPERBUILD47_GLOBAL_RECORDS=270/270"); console.log("SUPERBUILD47_PREVIOUS_AUTHORITATIVE_PRESERVED=18/18"); console.log("SUPERBUILD47_NEW_AUTHORITATIVE_ENABLED=57/270"); console.log("SUPERBUILD47_CUMULATIVE_AUTHORITATIVE_ENABLED=75/270"); console.log("SUPERBUILD47_MANAGEMENT_READY=75/270"); console.log("SUPERBUILD47_RETAINED_FAIL_CLOSED=195/270"); console.log("SUPERBUILD47_RESOLVER_ENABLED_SAMPLE=PASS"); console.log("SUPERBUILD47_RESOLVER_FAIL_CLOSED_SAMPLE=PASS"); console.log("SUPERBUILD47_PT_ES_PROVENANCE_CONTRACT=PASS"); console.log("S1_SAMPLE_PERCENT=1_UNCHANGED"); console.log("VISIBLE_CUTOVER=HARD_OFF");
