"use strict";
const assert=require("assert"); const fs=require("fs");
const {ClinicalManagementDependencyResolver}=require("../clinical_context/clinical_management_dependency_resolver");
const m49=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative210.phase22.local.json","utf8"));
const m50=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative270.phase23.local.json","utf8"));
const evidence=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_management_authoring_evidence.authoritative270.phase23.local.json","utf8"));
const supplement=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_registry_machine_native_supplement.phase23_management270_authoritative270.local.json","utf8"));
const report=JSON.parse(fs.readFileSync("functions/clinical_context/generated/global_clinical_context_superbuild50_management_final60_report.local.json","utf8"));
assert.strictEqual(m50.recordCount,270); assert.strictEqual(m50.enabledCount,270); assert.strictEqual(m50.managementReadyCount,270); assert.strictEqual(m50.failClosedCount,0); assert.strictEqual(m50.visibleCutoverEligibleCount,0);
assert.strictEqual(m50.previousAuthoritativeKeys.length,210); assert.strictEqual(m50.finalAuthoritativeKeys.length,60); assert.strictEqual(new Set(m50.finalAuthoritativeKeys).size,60); assert.strictEqual(m50.selectedAuthoritativeKeys.length,270);
assert.strictEqual(new Set(m50.records.map(r=>r.protocolKey)).size,270); assert.strictEqual(new Set(m50.records.map(r=>r.canonicalPathologyKey)).size,270); assert.strictEqual(new Set(m50.records.map(r=>r.managementRuleKey)).size,270);
const by49=new Map(m49.records.map(r=>[r.canonicalPathologyKey,r])); const by50=new Map(m50.records.map(r=>[r.canonicalPathologyKey,r]));
for(const k of m49.selectedAuthoritativeKeys){assert.deepStrictEqual(by50.get(k),by49.get(k),`M49 enabled record drift:${k}`);}
for(const r of m50.records){assert.strictEqual(r.enabled,true); assert.strictEqual(r.managementReady,true); assert.strictEqual(r.visibleCutoverEligible,false); assert.strictEqual(r.legacyManagementPromotedAutomatically,false); assert.strictEqual(r.managementInferredFromClassificationName,false); assert.strictEqual(r.clinicalSemanticInferencePerformed,false); assert(Array.isArray(r.provenance)&&r.provenance.length>0); for(const p of r.provenance){assert(/^https:\/\//.test(String(p.url||""))); assert.strictEqual(p.managementAuthorityValidated,true); assert.strictEqual(p.automaticPromotion,false);} for(const f of ["initialActions","definitiveActions","conditionalActions","contraindicatedActions","monitoring","reassessment","escalationCriteria"]){assert(Array.isArray(r[f])); for(const a of r[f]){assert(String(a.pt||"").trim()); assert(String(a.es||"").trim());}}}
assert.strictEqual(evidence.recordCount,270); assert.strictEqual(evidence.previousAuthoritativeCount,210); assert.strictEqual(evidence.finalAuthoritativeAuthoredCount,60); assert.strictEqual(evidence.cumulativeAuthoritativeCount,270); assert.strictEqual(evidence.inheritedFailClosedCount,0);
assert.strictEqual(supplement.managementRules.length,270); assert.strictEqual(supplement.cloudWriteAuthorized,false); assert.strictEqual(supplement.backendDeployAuthorized,false); assert.strictEqual(supplement.remoteConfigWriteAuthorized,false); assert.strictEqual(supplement.shadowS1Percent,1); assert.strictEqual(supplement.shadowPercentChangeAuthorized,false); assert.strictEqual(supplement.visibleCutover,false);
assert.strictEqual(report.authoritativeCurrentEnabled,270); assert.strictEqual(report.retainedFailClosed,0); assert.strictEqual(report.targetCohort,"EXACT_M49_DISABLED_SET_FROM_M50_R0_FINAL60_PACK"); assert.strictEqual(report.shadowS1Percent,1); assert.strictEqual(report.visibleCutover,false); assert.strictEqual(report.cloudMutation,false);
const resolver=new ClinicalManagementDependencyResolver();
for(const k of ["agitacao_psicomotora","cardio_trombose_protese_valvar","hemat_ptt_microangiopatia","infect_endocardite_infecciosa_aguda","pedi_cetoacidose_diabetica_edema_cerebral","psiqui_crise_suicida_alto_risco","volvulo_cecal"]){const rule=by50.get(k); const result=resolver.resolve({pathologyKey:k,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,true,k); assert.strictEqual(result.managementRuleKey,rule.managementRuleKey,k); assert.strictEqual(result.payload.authoringPolicy,"AUTHORITATIVE_CURRENT_OR_FAIL_CLOSED",k);}
console.log("SUPERBUILD50_CONTRACT=PASS"); console.log("SUPERBUILD50_GLOBAL_RECORDS=270/270"); console.log("SUPERBUILD50_PREVIOUS_AUTHORITATIVE_PRESERVED=210/210"); console.log("SUPERBUILD50_FINAL60_AUTHORITATIVE_ENABLED=60/60"); console.log("SUPERBUILD50_CUMULATIVE_AUTHORITATIVE_ENABLED=270/270"); console.log("SUPERBUILD50_MANAGEMENT_READY=270/270"); console.log("SUPERBUILD50_RETAINED_FAIL_CLOSED=0/270"); console.log("SUPERBUILD50_RESOLVER_ENABLED_SAMPLES=7/7_PASS"); console.log("SUPERBUILD50_PT_ES_PROVENANCE_CONTRACT=PASS"); console.log("S1_SAMPLE_PERCENT=1_UNCHANGED"); console.log("VISIBLE_CUTOVER=HARD_OFF");
