"use strict";
const assert=require("assert"); const fs=require("fs");
const {ClinicalManagementDependencyResolver}=require("../clinical_context/clinical_management_dependency_resolver");
const m47=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative75.phase20.local.json","utf8"));
const m48=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative150.phase21.local.json","utf8"));
const evidence=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_management_authoring_evidence.authoritative150.phase21.local.json","utf8"));
const supplement=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_registry_machine_native_supplement.phase21_management270_authoritative150.local.json","utf8"));
const report=JSON.parse(fs.readFileSync("functions/clinical_context/generated/global_clinical_context_superbuild48_management_next75_report.local.json","utf8"));
assert.strictEqual(m48.recordCount,270); assert.strictEqual(m48.enabledCount,150); assert.strictEqual(m48.managementReadyCount,150); assert.strictEqual(m48.failClosedCount,120); assert.strictEqual(m48.visibleCutoverEligibleCount,0);
assert.strictEqual(m48.newAuthoritativeKeys.length,75); assert.strictEqual(new Set(m48.newAuthoritativeKeys).size,75); assert.strictEqual(m48.selectedAuthoritativeKeys.length,150);
assert.strictEqual(new Set(m48.records.map(r=>r.protocolKey)).size,270); assert.strictEqual(new Set(m48.records.map(r=>r.canonicalPathologyKey)).size,270); assert.strictEqual(new Set(m48.records.map(r=>r.managementRuleKey)).size,270);
const by47=new Map(m47.records.map(r=>[r.canonicalPathologyKey,r])); const by48=new Map(m48.records.map(r=>[r.canonicalPathologyKey,r]));
for(const k of m47.selectedAuthoritativeKeys){assert.deepStrictEqual(by48.get(k),by47.get(k),`M47 enabled record drift:${k}`);}
const enabled=m48.records.filter(r=>r.enabled===true); const disabled=m48.records.filter(r=>r.enabled===false); assert.strictEqual(enabled.length,150); assert.strictEqual(disabled.length,120);
for(const r of enabled){assert.strictEqual(r.managementReady,true); assert.strictEqual(r.visibleCutoverEligible,false); assert.strictEqual(r.legacyManagementPromotedAutomatically,false); assert.strictEqual(r.managementInferredFromClassificationName,false); assert.strictEqual(r.clinicalSemanticInferencePerformed,false); assert(Array.isArray(r.provenance)&&r.provenance.length>0); for(const p of r.provenance){assert(/^https:\/\//.test(String(p.url||""))); assert.strictEqual(p.managementAuthorityValidated,true); assert.strictEqual(p.automaticPromotion,false);} for(const f of ["initialActions","definitiveActions","conditionalActions","contraindicatedActions","monitoring","reassessment","escalationCriteria"]){assert(Array.isArray(r[f])); for(const a of r[f]){assert(String(a.pt||"").trim()); assert(String(a.es||"").trim());}}}
assert.strictEqual(evidence.recordCount,270); assert.strictEqual(evidence.previousAuthoritativeCount,75); assert.strictEqual(evidence.newAuthoritativeAuthoredCount,75); assert.strictEqual(evidence.cumulativeAuthoritativeCount,150); assert.strictEqual(evidence.inheritedFailClosedCount,120);
assert.strictEqual(supplement.managementRules.length,270); assert.strictEqual(supplement.classifications.length,0); assert.strictEqual(supplement.actions.length,0); assert.strictEqual(supplement.content.length,0); assert.strictEqual(supplement.cloudWriteAuthorized,false); assert.strictEqual(supplement.backendDeployAuthorized,false); assert.strictEqual(supplement.remoteConfigWriteAuthorized,false); assert.strictEqual(supplement.shadowS1Percent,1); assert.strictEqual(supplement.shadowPercentChangeAuthorized,false); assert.strictEqual(supplement.visibleCutover,false);
assert.strictEqual(report.authoritativeCurrentEnabled,150); assert.strictEqual(report.retainedFailClosed,120); assert.strictEqual(report.shadowS1Percent,1); assert.strictEqual(report.visibleCutover,false); assert.strictEqual(report.cloudMutation,false); assert.strictEqual(report.newToxicologyKeys.length,38); assert.strictEqual(report.newNonToxicologyKeys.length,37);
const resolver=new ClinicalManagementDependencyResolver(); let rule=by48.get("intox_triciclicos"); let result=resolver.resolve({pathologyKey:rule.canonicalPathologyKey,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,true); assert.strictEqual(result.managementRuleKey,rule.managementRuleKey); assert.strictEqual(result.payload.authoringPolicy,"AUTHORITATIVE_CURRENT_OR_FAIL_CLOSED");
rule=disabled[0]; result=resolver.resolve({pathologyKey:rule.canonicalPathologyKey,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,false); assert.strictEqual(result.reason,"management_rule_not_registered");
const flat=k=>JSON.stringify(by48.get(k)).toLowerCase(); assert(flat("intox_monoxido_carbono").includes("100%")); assert(flat("intox_salicilatos").includes("hemodiálise")); assert(flat("lesao_renal_aguda").includes("draft público kdigo 2026")||flat("lesao_renal_aguda").includes("borrador público kdigo 2026")); assert(flat("faringite_estrep").includes("faringite viral")); assert(flat("volvulo_sigmoide").includes("descompressão endoscópica"));
console.log("SUPERBUILD48_CONTRACT=PASS"); console.log("SUPERBUILD48_GLOBAL_RECORDS=270/270"); console.log("SUPERBUILD48_PREVIOUS_AUTHORITATIVE_PRESERVED=75/75"); console.log("SUPERBUILD48_NEW_AUTHORITATIVE_ENABLED=75/270"); console.log("SUPERBUILD48_CUMULATIVE_AUTHORITATIVE_ENABLED=150/270"); console.log("SUPERBUILD48_MANAGEMENT_READY=150/270"); console.log("SUPERBUILD48_RETAINED_FAIL_CLOSED=120/270"); console.log("SUPERBUILD48_TOXICOLOGY_NEW=38/38"); console.log("SUPERBUILD48_NONTOXICOLOGY_NEW=37/37"); console.log("SUPERBUILD48_RESOLVER_ENABLED_SAMPLE=PASS"); console.log("SUPERBUILD48_RESOLVER_FAIL_CLOSED_SAMPLE=PASS"); console.log("SUPERBUILD48_PT_ES_PROVENANCE_CONTRACT=PASS"); console.log("S1_SAMPLE_PERCENT=1_UNCHANGED"); console.log("VISIBLE_CUTOVER=HARD_OFF");
