"use strict";
const assert=require("assert"); const fs=require("fs");
const {ClinicalManagementDependencyResolver}=require("../clinical_context/clinical_management_dependency_resolver");
const m48=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative150.phase21.local.json","utf8"));
const m49=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_machine_management.authoritative210.phase22.local.json","utf8"));
const evidence=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_management_authoring_evidence.authoritative210.phase22.local.json","utf8"));
const supplement=JSON.parse(fs.readFileSync("functions/clinical_context/generated/clinical_registry_machine_native_supplement.phase22_management270_authoritative210.local.json","utf8"));
const report=JSON.parse(fs.readFileSync("functions/clinical_context/generated/global_clinical_context_superbuild49_management_next60_report.local.json","utf8"));
assert.strictEqual(m49.recordCount,270); assert.strictEqual(m49.enabledCount,210); assert.strictEqual(m49.managementReadyCount,210); assert.strictEqual(m49.failClosedCount,60); assert.strictEqual(m49.visibleCutoverEligibleCount,0);
assert.strictEqual(m49.previousAuthoritativeKeys.length,150); assert.strictEqual(m49.newAuthoritativeKeys.length,60); assert.strictEqual(new Set(m49.newAuthoritativeKeys).size,60); assert.strictEqual(m49.selectedAuthoritativeKeys.length,210);
assert.strictEqual(new Set(m49.records.map(r=>r.protocolKey)).size,270); assert.strictEqual(new Set(m49.records.map(r=>r.canonicalPathologyKey)).size,270); assert.strictEqual(new Set(m49.records.map(r=>r.managementRuleKey)).size,270);
const by48=new Map(m48.records.map(r=>[r.canonicalPathologyKey,r])); const by49=new Map(m49.records.map(r=>[r.canonicalPathologyKey,r]));
for(const k of m48.selectedAuthoritativeKeys){assert.deepStrictEqual(by49.get(k),by48.get(k),`M48 enabled record drift:${k}`);}
const enabled=m49.records.filter(r=>r.enabled===true); const disabled=m49.records.filter(r=>r.enabled===false); assert.strictEqual(enabled.length,210); assert.strictEqual(disabled.length,60);
for(const r of enabled){assert.strictEqual(r.managementReady,true); assert.strictEqual(r.visibleCutoverEligible,false); assert.strictEqual(r.legacyManagementPromotedAutomatically,false); assert.strictEqual(r.managementInferredFromClassificationName,false); assert.strictEqual(r.clinicalSemanticInferencePerformed,false); assert(Array.isArray(r.provenance)&&r.provenance.length>0); for(const p of r.provenance){assert(/^https:\/\//.test(String(p.url||""))); assert.strictEqual(p.managementAuthorityValidated,true); assert.strictEqual(p.automaticPromotion,false);} for(const f of ["initialActions","definitiveActions","conditionalActions","contraindicatedActions","monitoring","reassessment","escalationCriteria"]){assert(Array.isArray(r[f])); for(const a of r[f]){assert(String(a.pt||"").trim()); assert(String(a.es||"").trim());}}}
assert.strictEqual(evidence.recordCount,270); assert.strictEqual(evidence.previousAuthoritativeCount,150); assert.strictEqual(evidence.newAuthoritativeAuthoredCount,60); assert.strictEqual(evidence.cumulativeAuthoritativeCount,210); assert.strictEqual(evidence.inheritedFailClosedCount,60);
assert.strictEqual(supplement.managementRules.length,270); assert.strictEqual(supplement.cloudWriteAuthorized,false); assert.strictEqual(supplement.backendDeployAuthorized,false); assert.strictEqual(supplement.remoteConfigWriteAuthorized,false); assert.strictEqual(supplement.shadowS1Percent,1); assert.strictEqual(supplement.shadowPercentChangeAuthorized,false); assert.strictEqual(supplement.visibleCutover,false);
assert.strictEqual(report.authoritativeCurrentEnabled,210); assert.strictEqual(report.retainedFailClosed,60); assert.strictEqual(report.targetCohort,"SIMULATION_IDS_201_TO_240_PLUS_251_TO_270"); assert.strictEqual(report.shadowS1Percent,1); assert.strictEqual(report.visibleCutover,false); assert.strictEqual(report.cloudMutation,false);
const resolver=new ClinicalManagementDependencyResolver();
for(const k of ["neuro_guillain_barre_insuficiencia_respiratoria","infect_fasciite_necrosante","cirurg_isquemia_aguda_membro","psiqui_tept","psiqui_psicose_pos_parto"]){const rule=by49.get(k); const result=resolver.resolve({pathologyKey:k,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,true,k); assert.strictEqual(result.managementRuleKey,rule.managementRuleKey,k); assert.strictEqual(result.payload.authoringPolicy,"AUTHORITATIVE_CURRENT_OR_FAIL_CLOSED",k);}
let rule=disabled[0]; let result=resolver.resolve({pathologyKey:rule.canonicalPathologyKey,managementRules:[rule],classificationResult:{resolved:false,missingFacts:[]}}); assert.strictEqual(result.resolved,false); assert.strictEqual(result.reason,"management_rule_not_registered");
const flat=k=>JSON.stringify(by49.get(k)).toLowerCase();
assert(flat("neuro_hemorragia_subaracnoidea_aneurismatica").includes("nimodipino")); assert(flat("endocr_crise_feocromocitoma").includes("bloqueio alfa")); assert(flat("cirurg_torcao_testicular_aguda").includes("doppler")); assert(flat("oftalmo_oclusao_arteria_central_retina").includes("massagem ocular")); assert(flat("psiqui_tept").includes("benzodia")); assert(flat("psiqui_bipolar_episodio_depressivo").includes("monoterapia")); assert(flat("psiqui_tea_avaliacao").includes("características centrais"));
console.log("SUPERBUILD49_CONTRACT=PASS"); console.log("SUPERBUILD49_GLOBAL_RECORDS=270/270"); console.log("SUPERBUILD49_PREVIOUS_AUTHORITATIVE_PRESERVED=150/150"); console.log("SUPERBUILD49_NEW_AUTHORITATIVE_ENABLED=60/270"); console.log("SUPERBUILD49_CUMULATIVE_AUTHORITATIVE_ENABLED=210/270"); console.log("SUPERBUILD49_MANAGEMENT_READY=210/270"); console.log("SUPERBUILD49_RETAINED_FAIL_CLOSED=60/270"); console.log("SUPERBUILD49_RESOLVER_ENABLED_SAMPLES=5/5_PASS"); console.log("SUPERBUILD49_RESOLVER_FAIL_CLOSED_SAMPLE=PASS"); console.log("SUPERBUILD49_PT_ES_PROVENANCE_CONTRACT=PASS"); console.log("S1_SAMPLE_PERCENT=1_UNCHANGED"); console.log("VISIBLE_CUTOVER=HARD_OFF");
