'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {Readable}=require('node:stream');
const {fixture}=require('./transcription_durable_queue.test');
const {longAac}=require('./test/long_recording_fixture');
const {LogicalRecordingQueue}=require('./logical_recording_queue');
const {MedCasesTranscriptionService}=require('./medcases_transcription_service');
const {validProof}=require('./audio_media_budget');
const {adts}=require('./test/adts_fixture');
const fs=require('node:fs'),path=require('node:path');
const speech=adts(fs.readFileSync(path.join(__dirname,'test/fixtures/synthetic-speech-2s-22050.m4a')));
const {adtsRecordingStructure}=require('./adts_recording_structure');
const parsed=adtsRecordingStructure(speech);
const frames=parsed.frames.map(([off,len])=>speech.subarray(off-7,off+len));
const count=Math.floor(1080*parsed.rate/1024);
const spoken18=Buffer.concat(Array.from({length:count},(_,i)=>frames[i%frames.length]));
for(const [format,bytes] of [['legacy MP4',longAac(1080)],['continuous ADTS synthetic speech',spoken18]])test(`18 minute ${format} pipeline: one upload/proof, mocked provider job and persisted result on replay`,async()=>{
 const f=fixture();f.job.provider='assemblyai';f.job.singleAudio=true;f.job.locale='pt';
 const op=f.rows.get('usageReservations/'+'b'.repeat(64));op.maximumMs=1080000;
 let uploads=0,submits=0,claims=0;
 const provider={async upload(stream){uploads++;for await(const c of stream)assert(c.length);return 'https://synthetic.invalid/audio';},async submit(){submits++;return {providerTranscriptId:'synthetic-id'};},async poll(){return {status:'completed',text:'Synthetic transcript',words:[],utterances:[]};},async remove(){}};
 f.storage.getStream=async key=>({body:Readable.from([await f.storage.get(key)])});
 const originalClaim=f.owner.claimExecution;f.owner.claimExecution=async(...args)=>{claims++;assert(validProof(args[3]));assert(Math.abs(args[3].durationMs-1080000)<50);return originalClaim(...args);};
 const worker=new LogicalRecordingQueue({db:f.db,storage:f.storage,owner:f.owner,centralService:new MedCasesTranscriptionService({providers:{assemblyai:provider}}),assemble:()=>{throw Error('LEGACY_ASSEMBLER_MUST_NOT_RUN');}});
 await f.queue.enqueue(f.jobRef,f.job,0,bytes,Date.now());
 await worker.process(f.jobRef,f.job);await worker.process(f.jobRef,f.job);
 assert.equal(uploads,1);assert.equal(submits,1);assert.equal(claims,1);
 assert.equal((await f.jobRef.get()).data().state,'completed');assert.equal((await f.segment.get()).data().transcript,'Synthetic transcript');
 await worker.process(f.jobRef,(await f.jobRef.get()).data());assert.equal(submits,1);
});
