'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {TranscriptionAttemptLedger}=require('./transcription_attempt_ledger');
const {database}=require('./test/transaction_fixture');
function fixture(){const db=database();const raw=db.collection;function collection(path){const col=raw(path),doc=col.doc;return {...col,doc(id){const ref=doc(id);return {...ref,collection:name=>collection(`${ref.path}/${name}`)};}};}db.collection=collection;return {db,l:new TranscriptionAttemptLedger({db,now:()=>100}),m:{attemptId:'attempt-1',sourceId:'source-1',sessionId:'session-1',platform:'ios',locale:'pt',appVersion:'7.0.2',buildNumber:'1709'}};}
test('concurrent create preserves one attempt before any eligibility or quota',async()=>{const {db,l,m}=fixture();await Promise.all(Array.from({length:20},()=>l.create('A',m)));assert.equal([...db.records.keys()].filter(k=>k.startsWith('transcriptionAttempts/')).length,1);assert.equal((await l.ref('A',m.attemptId).get()).data().state,'REQUESTED');});
test('same ID cannot change source',async()=>{const {l,m}=fixture();await l.create('A',m);await assert.rejects(l.create('A',{...m,sourceId:'other'}),/BINDING/);});
test('another user cannot mutate owner attempt',async()=>{const {l,m}=fixture();await l.create('A',m);await assert.rejects(l.advance('B',m.attemptId,{eventId:'failure',state:'FAILED',reasonCode:'UPLOAD_FAILURE'}),/NOT_OWNED/);});
test('pre-job failure is durable and incident increments once under retries',async()=>{const {db,l,m}=fixture();await l.create('A',m);await Promise.all(Array.from({length:20},()=>l.advance('A',m.attemptId,{eventId:'failure',state:'FAILED',stage:'VALIDATING',reasonCode:'ELIGIBILITY_FAILURE'},{origin:'client'})));const v=(await l.ref('A',m.attemptId).get()).data();assert.equal(v.state,'FAILED');assert.equal(v.lastStage,'VALIDATING');assert.equal([...db.records].find(([k])=>k.startsWith('admin_incidents/'))[1].count,1);});
test('unknown payload fields and raw error text cannot persist',async()=>{const {l,m}=fixture();await assert.rejects(l.create('A',{...m,transcript:'private'}),/METADATA/);await l.create('A',m);await assert.rejects(l.advance('A',m.attemptId,{eventId:'x',state:'FAILED',reasonCode:'secret error'}),/EVENT/);await assert.rejects(l.advance('A',m.attemptId,{eventId:'x',state:'PROCESSING',raw:'secret'}),/EVENT/);});
test('client cannot manufacture provider completion',async()=>{const {l,m}=fixture();await l.create('A',m);await assert.rejects(l.advance('A',m.attemptId,{eventId:'x',state:'COMPLETED'},{origin:'client'}),/FORBIDDEN/);});
test('late client failure does not replace remote processing or completed result',async()=>{const {l,m}=fixture();await l.create('A',m);await l.advance('A',m.attemptId,{eventId:'job',state:'JOB_CREATED'});await l.advance('A',m.attemptId,{eventId:'client-timeout',state:'FAILED',reasonCode:'CLIENT_TIMEOUT'},{origin:'client'});assert.equal((await l.ref('A',m.attemptId).get()).data().state,'JOB_CREATED');const ignored=(await l.ref('A',m.attemptId).get()).data().timeline.at(-1);assert.equal(ignored.reasonCode,'CLIENT_TIMEOUT');assert.equal(ignored.applied,false);await l.advance('A',m.attemptId,{eventId:'done',state:'COMPLETED'});await l.advance('A',m.attemptId,{eventId:'late',state:'PROCESSING'});assert.equal((await l.ref('A',m.attemptId).get()).data().state,'COMPLETED');});
test('reordered progress cannot regress a later stage',async()=>{const {l,m}=fixture();await l.create('A',m);await l.advance('A',m.attemptId,{eventId:'p',state:'PROCESSING'});await l.advance('A',m.attemptId,{eventId:'u',state:'UPLOADING'});assert.equal((await l.ref('A',m.attemptId).get()).data().state,'PROCESSING');});
test('pre-job deadline records recoverable incident but never overrides a bound or fresh attempt',async()=>{
 const {l,m}=fixture();await l.create('A',m);await l.create('B',{...m,attemptId:'bound'});await l.bind('B','bound',{jobId:'a'.repeat(64)});
 l.now=()=>1000001;await l.create('C',{...m,attemptId:'fresh'});await l.expireUnbound();
 assert.equal((await l.ref('A',m.attemptId).get()).data().state,'RECOVERABLE_FAILED');
 assert.equal((await l.ref('B','bound').get()).data().state,'REQUESTED');
 assert.equal((await l.ref('C','fresh').get()).data().state,'REQUESTED');
 await l.advance('A',m.attemptId,{eventId:'recovered',state:'JOB_CREATED'});assert.equal((await l.ref('A',m.attemptId).get()).data().state,'JOB_CREATED');
});
