'use strict';
// Fictional teaching sources: no patient data, no clinical recommendations.
// Complement, rather than replace, every R2.2 source and negative observation.
const {corpus:previous}=require('./oral_exam_r22_corpus');
const pairs=[
 ['Hipótese é definido como uma explicação provisória que ainda precisa ser confrontada com evidências. Uma hipótese não se torna confirmação apenas por ser repetida.\n\nA lista de campos da aula contém três categorias: observação, interpretação e incerteza. Nenhuma categoria autoriza preencher informação ausente.\n\nNeste exercício de documentação, separar o que foi observado do que foi interpretado permite reconhecer as limitações da fonte. Um campo não preenchido não demonstra um resultado normal.',
 'Hipótesis se define como una explicación provisional que todavía debe contrastarse con evidencias. Una hipótesis no se convierte en confirmación por repetirse.\n\nLa lista de campos de la clase contiene tres categorías: observación, interpretación e incertidumbre. Ninguna categoría autoriza completar información ausente.\n\nEn este ejercicio de documentación, separar lo observado de lo interpretado permite reconocer las limitaciones de la fuente. Un campo vacío no demuestra un resultado normal.'],
 ['Registro é definido como a preservação do relato atribuído à sua fonte, incluindo as correções explicitamente realizadas. Não equivale a confirmar a veracidade do relato.\n\nNo exemplo fictício, Teste-A usa 0,5 unidades a cada 12 horas. A pessoa corrigiu esse valor para 5 unidades a cada 24 horas no mesmo relato. Trata-se de um exercício de preservação textual, não uma prescrição.\n\nA lista de verificações contém três itens: unidade, intervalo e correção. O objetivo é não transformar a primeira dose citada na dose final quando a própria fonte a corrigiu.',
 'Registro se define como la preservación del relato atribuido a su fuente, incluidas las correcciones explícitas. No equivale a confirmar la veracidad del relato.\n\nEn el ejemplo ficticio, Prueba-A usa 0,5 unidades cada 12 horas. La persona corrigió ese valor a 5 unidades cada 24 horas en el mismo relato. Es un ejercicio de preservación textual, no una prescripción.\n\nLa lista de verificaciones contiene tres elementos: unidad, intervalo y corrección. El objetivo es no convertir la primera dosis citada en la dosis final cuando la propia fuente la corrigió.'],
 ['Rastreabilidade é definido como a possibilidade de identificar o trecho que sustenta uma afirmação. A referência precisa corresponder à afirmação, não apenas tratar do mesmo assunto.\n\nA lista de evidências contém três elementos: texto original, localização e autoria quando informada. Não foi estabelecida uma ordem de importância.\n\nEm um resumo, mudar a ordem dos tópicos pode ser útil, mas não autoriza atribuir a uma pessoa o relato de outra. Quando a autoria não está disponível, ela deve permanecer desconhecida.',
 'Trazabilidad se define como la posibilidad de identificar el fragmento que respalda una afirmación. La referencia debe corresponder a la afirmación, no solo tratar el mismo tema.\n\nLa lista de evidencias contiene tres elementos: texto original, ubicación y autoría cuando esté informada. No se estableció un orden de importancia.\n\nEn un resumen, cambiar el orden de los temas puede ser útil, pero no permite atribuir a una persona el relato de otra. Si la autoría no está disponible, debe permanecer desconocida.'],
 ['O composto fictício Lume pode aumentar a medida de contraste em alguns experimentos. A aula não afirma que isso aconteça sempre nem que demonstre benefício clínico.\n\nA lista de limitações contém dois elementos: ausência de confirmação e dependência do contexto experimental. Não foi definida prioridade entre eles.\n\nOs resultados descritos pertencem apenas ao exercício apresentado. A explicação não estabelece dose, indicação, causalidade ou recomendação para pacientes. Esses campos não podem ser inferidos da alteração de uma medida.',
 'El compuesto ficticio Lume puede aumentar la medida de contraste en algunos experimentos. La clase no afirma que ocurra siempre ni que demuestre beneficio clínico.\n\nLa lista de limitaciones contiene dos elementos: ausencia de confirmación y dependencia del contexto experimental. No se definió prioridad entre ellos.\n\nLos resultados descritos pertenecen solo al ejercicio presentado. La explicación no establece dosis, indicación, causalidad ni recomendaciones para pacientes. Esos campos no pueden inferirse de un cambio en una medida.'],
 ['No cenário didático, se a fonte estiver disponível, então seguir a etapa Registro. Sem a fonte, Registro não está autorizado nesse exercício.\n\nA etapa Comparação depende da conclusão de Registro; a fonte não define outra condição. Comparar sem o registro concluído viola a sequência ensinada.\n\nA aula usa etapas como exemplo de dependência explícita. Não há horários, durações ou efeitos clínicos descritos. O raciocínio esperado conecta a condição inicial à dependência seguinte, sem preencher lacunas.',
 'En el escenario didáctico, si la fuente está disponible, entonces seguir la etapa Registro. Sin la fuente, Registro no está autorizado en este ejercicio.\n\nLa etapa Comparación depende de la finalización de Registro; la fuente no define otra condición. Comparar sin el registro completo viola la secuencia enseñada.\n\nLa clase utiliza etapas como ejemplo de dependencia explícita. No hay horarios, duraciones ni efectos clínicos descritos. El razonamiento esperado conecta la condición inicial con la dependencia siguiente, sin completar lagunas.'],
 ['Ambiguidade é definido como a existência de mais de uma interpretação possível que a fonte não permite resolver. Escolher uma delas sem evidência acrescenta informação.\n\nEle disse que isso havia melhorado. Não se sabe a quem ele se referiu, qual medida mudou nem em que momento. A aula apresenta esse trecho como exemplo de referência não resolvida.\n\nA lista de informações ausentes contém três itens: sujeito, medida e momento. Não atribuir um horário ou uma identidade a partir de suposições. O material disponível permite reconhecer a lacuna, não corrigi-la.',
 'Ambigüedad se define como la existencia de más de una interpretación posible que la fuente no permite resolver. Elegir una sin evidencia añade información.\n\nDijo que eso había mejorado. No se sabe a quién se refería, qué medida cambió ni cuándo. La clase presenta este fragmento como ejemplo de referencia no resuelta.\n\nLa lista de datos ausentes contiene tres elementos: sujeto, medida y momento. No atribuir un horario ni una identidad a partir de suposiciones. El material disponible permite reconocer la laguna, no corregirla.'],
];
module.exports={corpus:[...previous,...pairs.flatMap((pair,i)=>pair.map((rawTranscript,j)=>({id:`R23_LECTURE_${i}_${j?'ES':'PT'}`,locale:j?'es':'pt',rawTranscript,questionCount:4,difficultyTarget:'MIXED',scenario:100+i}))) ]};
module.exports.corpus.push(
 {id:'R23_COMPARISON_PT',locale:'pt',questionCount:3,difficultyTarget:'MEDIUM',rawTranscript:'O conceito Observado é verificável diretamente, enquanto o conceito Relatado não é verificável diretamente no exercício. Essa diferença pertence à convenção didática desta aula, não a uma classificação universal. O registro de um relato continua válido como relato, mesmo sem observação independente.\n\nO objetivo da comparação é manter a atribuição correta de cada afirmação. Trocar as categorias modifica o grau de evidência documentado. A aula não autoriza escolher uma versão como verdadeira quando as fontes divergem.'},
 {id:'R23_COMPARISON_ES',locale:'es',questionCount:3,difficultyTarget:'MEDIUM',rawTranscript:'El concepto Observado es verificable directamente, mientras que el concepto Relatado no es verificable directamente en el ejercicio. Esa diferencia pertenece a la convención didáctica de esta clase, no a una clasificación universal. El registro de un relato sigue siendo válido como relato, aun sin observación independiente.\n\nEl objetivo de la comparación es mantener la atribución correcta de cada afirmación. Intercambiar las categorías modifica el grado de evidencia documentado. La clase no autoriza elegir una versión como verdadera cuando las fuentes discrepan.'},
 {id:'R23_SEQUENCE_PT',locale:'pt',questionCount:3,difficultyTarget:'MEDIUM',rawTranscript:'Primeiro identificar a fonte, depois separar observação de interpretação, e por último revisar as incertezas. Não foram informados horários ou prazos para essas etapas. A revisão final depende de manter os dois tipos de informação separados no registro anterior.\n\nEssa sequência é o método apresentado para revisar um relato no exercício. Revisar não significa completar informação ausente. Se a autoria não estiver declarada, o registro deve conservar essa limitação, sem atribuí-la a outro participante.'},
 {id:'R23_SEQUENCE_ES',locale:'es',questionCount:3,difficultyTarget:'MEDIUM',rawTranscript:'Primero identificar la fuente, después separar observación de interpretación y por último revisar las incertidumbres. No se informaron horarios ni plazos para esas etapas. La revisión final depende de mantener los dos tipos de información separados en el registro anterior.\n\nEsa secuencia es el método presentado para revisar un relato en el ejercicio. Revisar no significa completar información ausente. Si la autoría no está declarada, el registro debe conservar esa limitación, sin atribuirla a otro participante.'}
);
