'use strict';
// Fictional concepts only. No patient data or clinical guidance. Same taught
// concepts in PT/ES; questions are generated independently, not translated.
const pairs=[
 ['O composto fictício Alfa pode aumentar a medida Z em alguns casos. Isso não acontece sempre.','El compuesto ficticio Alfa puede aumentar la medida Z en algunos casos. Esto no ocurre siempre.'],
 ['Foi sugerido que Beta estava relacionado a Gama. A relação não foi confirmada.','Se sugirió que Beta estaba relacionado con Gamma. La relación no fue confirmada.'],
 ['Ontem o sinal estava ausente, hoje estava presente. Essa evolução não é necessariamente uma contradição.','Ayer la señal estaba ausente, hoy estaba presente. Esta evolución no es necesariamente una contradicción.'],
 ['O conceito A é reversível, enquanto o conceito B não é reversível. Essa é a diferença ensinada entre ambos.','El concepto A es reversible, mientras que el concepto B no es reversible. Esa es la diferencia enseñada entre ambos.'],
 ['Primeiro registrar X, depois comparar Y, e por último revisar Z. Não foram informados horários.','Primero registrar X, después comparar Y y por último revisar Z. No se informaron horarios.'],
 ['No sistema fictício, apertar o botão causa o acendimento da lâmpada, mas somente quando a energia está ligada.','En el sistema ficticio, pulsar el botón causa el encendido de la lámpara, pero solo cuando la energía está conectada.'],
 ['A lista ensinada contém três categorias: Alfa, Beta e Gama. Nenhuma ordem de importância foi definida.','La lista enseñada contiene tres categorías: Alfa, Beta y Gamma. No se definió ningún orden de importancia.'],
 ['Não foram mencionadas alergias nem resultados de exames. Ausência de informação não significa ausência de alergia ou exame normal.','No se mencionaron alergias ni resultados de pruebas. La ausencia de información no significa ausencia de alergia ni prueba normal.'],
 ['Ele disse que isso melhorou, mas não esclareceu quem, o que melhorou ou quando. Não há outros dados.','Dijo que eso mejoró, pero no aclaró quién, qué mejoró ni cuándo. No hay otros datos.'],
 ['No exemplo fictício, Teste-A usa 0,5 unidades a cada 12 horas. O exemplo não se refere a um paciente. Não converter unidades.','En el ejemplo ficticio, Prueba-A usa 0,5 unidades cada 12 horas. El ejemplo no se refiere a un paciente. No convertir unidades.'],
 ['No cenário didático, se a condição X estiver presente, então seguir a etapa A. Sem X, a etapa A não está indicada nesse cenário.\n\nA etapa B depende da conclusão de A; a fonte não define outra condição.','En el escenario didáctico, si la condición X está presente, entonces seguir la etapa A. Sin X, la etapa A no está indicada en ese escenario.\n\nLa etapa B depende de la finalización de A; la fuente no define otra condición.'],
 ['A etapa inicial registra as observações, enquanto a etapa final compara os registros.\n\nPrimeiro registrar, depois comparar. Comparar depende de existirem registros; essa relação explica a sequência.','La etapa inicial registra las observaciones, mientras que la etapa final compara los registros.\n\nPrimero registrar, después comparar. Comparar depende de que existan registros; esa relación explica la secuencia.'],
];
module.exports={corpus:pairs.flatMap((p,i)=>p.map((rawTranscript,j)=>({id:`ORAL_${i}_${j?'ES':'PT'}`,locale:j?'es':'pt',rawTranscript,questionCount:3,difficultyTarget:i>=10?'HARD':i===3||i===4||i===5?'MEDIUM':'EASY',expectedInsufficient:i===8,scenario:i}))) };

const richHard=[
 ["No curso fictício Nexo, a fase Registro coleta observações sem interpretá-las. A fase Comparação confronta registros já concluídos. Comparação depende de Registro: sem registros concluídos, não há material para comparar.\n\nO modo Rápido executa Registro e depois Comparação, sem uma revisão intermediária. O modo Seguro executa Registro, depois Revisão e somente depois Comparação. A Revisão identifica campos vazios antes de comparar.\n\nSe a Revisão encontrar um campo vazio, então o modo Seguro retorna a Registro; Comparação fica suspensa até a correção e nova Revisão. A ausência de revisão no modo Rápido não prova que seus registros tenham erros.\n\nAmbos os modos exigem registros concluídos para Comparação. A diferença é a checagem intermediária e o retorno condicionado no modo Seguro. A fonte não afirma que um modo seja sempre superior.",
 "En el curso ficticio Nexo, la fase Registro recoge observaciones sin interpretarlas. La fase Comparación contrasta registros ya completados. Comparación depende de Registro: sin registros completos no hay material para comparar.\n\nEl modo Rápido ejecuta Registro y después Comparación, sin revisión intermedia. El modo Seguro ejecuta Registro, luego Revisión y solo después Comparación. Revisión identifica campos vacíos antes de comparar.\n\nSi Revisión encuentra un campo vacío, entonces el modo Seguro vuelve a Registro; Comparación queda suspendida hasta la corrección y otra Revisión. La ausencia de revisión en modo Rápido no prueba que sus registros tengan errores.\n\nAmbos modos requieren registros completos para Comparación. La diferencia es la comprobación intermedia y el retorno condicionado en modo Seguro. La fuente no afirma que un modo sea siempre superior."],
 ["Na máquina fictícia Lume, ligar a fonte de energia permite alimentar a lâmpada, mas não a acende sozinho. O botão deve estar pressionado e a tampa deve estar fechada para a lâmpada acender.\n\nSe a tampa abrir enquanto o botão está pressionado, então o circuito interrompe a alimentação da lâmpada. Essa interrupção causa o apagamento enquanto a tampa permanecer aberta.\n\nFechar a tampa não restaura automaticamente a luz após essa interrupção: é necessário soltar o botão e pressioná-lo novamente. A fonte de energia deve continuar ligada nessa retomada.\n\nA partida inicial e a retomada exigem energia ligada, tampa fechada e botão pressionado. A retomada após abertura exige também o ciclo de soltar e pressionar. Essa é a diferença explícita entre as duas situações; a fonte não explica o mecanismo interno.",
 "En la máquina ficticia Lume, conectar la fuente de energía permite alimentar la lámpara, pero no la enciende por sí solo. El botón debe estar pulsado y la tapa cerrada para que la lámpara se encienda.\n\nSi la tapa se abre mientras el botón está pulsado, entonces el circuito interrumpe la alimentación de la lámpara. Esa interrupción causa el apagado mientras la tapa permanezca abierta.\n\nCerrar la tapa no restaura automáticamente la luz tras esa interrupción: hay que soltar el botón y pulsarlo de nuevo. La fuente de energía debe seguir conectada en esa reanudación.\n\nEl inicio y la reanudación requieren energía conectada, tapa cerrada y botón pulsado. La reanudación tras apertura requiere además soltar y volver a pulsar. Esa es la diferencia explícita entre ambas situaciones; la fuente no explica el mecanismo interno."],
];
module.exports.corpus.push(...richHard.flatMap((p,i)=>p.map((rawTranscript,j)=>({id:`ORAL_RICH_${i}_${j?'ES':'PT'}`,locale:j?'es':'pt',rawTranscript,questionCount:3,difficultyTarget:'HARD',expectedInsufficient:false,scenario:12+i}))));
