import fs from 'node:fs';
const inheritedBaselineHashes=JSON.parse(fs.readFileSync(new URL('./migration-baseline-allowlist.json',import.meta.url)));
import {createHash} from 'node:crypto';
export const extraCollections=['clinical_projection_registry','clinical_legacy_protocols'];
export const canonical=v=>JSON.stringify(sort(v));function sort(v){return Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;}
export const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const require=(ok,code)=>{if(!ok)throw Error(code)};
export function projectionMetadata(rows){const owners=rows.clinical_identity_registry.map(r=>r.canonicalKey).sort();const byOwner=new Map(rows.clinical_projection_registry.map(r=>[r.canonicalPathologyKey,r]));const availability=[];const surfaceOwnerIds={};
 for(const owner of owners){const r=byOwner.get(owner);require(r,'owner_projection_record_missing');const inherited=r.migrationStatus==='MIGRATION_BASELINE_INHERITED';const availableModes={},referenceState={};for(const mode of ['study','plantao']){availableModes[mode]={};referenceState[mode]={};for(const locale of ['pt','es']){const p=r.payload?.[locale]?.[mode+'Projection'];availableModes[mode][locale]=p!=null;referenceState[mode][locale]=p==null?'not_available':inherited?r.referenceState?.[mode]?.[locale]:'present';}}availability.push({ownerId:owner,availableModes,referenceState,routeKind:inherited?'legacy_source_context':'authored_projection'});}
 for(const mode of ['study','plantao'])for(const l of ['pt','es'])surfaceOwnerIds[mode+'_'+l]=availability.filter(o=>o.availableModes[mode][l]).map(o=>o.ownerId);
 return {owners:availability,surfaceOwnerIds,surfaceSetHashes:Object.fromEntries(Object.entries(surfaceOwnerIds).map(([k,v])=>[k,hash(v)])),studyPtCount:surfaceOwnerIds.study_pt.length,studyEsCount:surfaceOwnerIds.study_es.length,plantaoPtCount:surfaceOwnerIds.plantao_pt.length,plantaoEsCount:surfaceOwnerIds.plantao_es.length};}
export function validateFunctional({manifest:m,chunks},legacyCollections,validateStrict){require(m.schemaVersion===2&&['DRAFT','ACTIVE'].includes(m.status),'schema_status');require(/^[A-Za-z0-9._-]{1,120}$/.test(m.contentVersion),'version');require(m.minimumClientBuild===1717,'client_build');const collections=[...legacyCollections,...extraCollections],rows=Object.fromEntries(collections.map(c=>[c,[]])),ids=new Set();require(m.chunks.length>0&&m.chunks.length<=5000,'chunk_count');
 for(const d of m.chunks){require(/^[A-Za-z0-9._-]{1,120}$/.test(d.id)&&!ids.has(d.id)&&collections.includes(d.collection),'chunk_id');ids.add(d.id);const json=chunks[d.id]?.json;require(typeof json==='string'&&Buffer.byteLength(json)<=800000&&createHash('sha256').update(json).digest('hex')===d.sha256,'chunk_hash');const part=JSON.parse(json);require(Array.isArray(part)&&part.length===d.count,'row_count');rows[d.collection].push(...part);}
 require(ids.size===Object.keys(chunks).length,'extra_chunk');const owners=new Set(rows.clinical_identity_registry.map(r=>r.canonicalKey));require(owners.size===m.ownerCount&&owners.size===rows.clinical_identity_registry.length,'owner_count');
 for(const c of collections){require(rows[c].length===m.counts[c],'collection_count');const keys=new Set();for(const r of rows[c]){const owner=c==='clinical_identity_registry'?r.canonicalKey:c==='clinical_action_registry'?(r.match?.canonicalPathologyKey??r.canonicalPathologyKey):r.canonicalPathologyKey;require(owners.has(owner)&&r.enabled!==false,'orphan_or_disabled');if(c==='clinical_legacy_protocols'||(c==='clinical_projection_registry'&&r.migrationStatus==='MIGRATION_BASELINE_INHERITED')){require(!keys.has(owner),'duplicate_owner_projection');keys.add(owner);}}}
 const authored=rows.clinical_projection_registry.filter(r=>r.migrationStatus!=='MIGRATION_BASELINE_INHERITED');if(authored.length){const subset=new Set(authored.map(r=>r.canonicalPathologyKey));const strictRows=Object.fromEntries(legacyCollections.map(c=>[c,c==='clinical_identity_registry'?rows[c].filter(r=>subset.has(r.canonicalKey)):c==='clinical_content_registry'?authored:[]]));validateStrict(strictRows);}
 for(const r of rows.clinical_projection_registry.filter(r=>r.migrationStatus==='MIGRATION_BASELINE_INHERITED')){const p=r.payload;require(r.historicalApprovalHash===null&&r.migrationBaselineHash===hash(p),'migration_hash');require(r.sourceRuntimeHash===r.migrationBaselineHash,'source_target_hash');require(p.ownerId===r.canonicalPathologyKey,'projection_owner');let count=0;for(const mode of ['study','plantao'])for(const locale of ['pt','es']){const x=p[locale]?.[mode+'Projection'];if(x==null)continue;count++;require(x.mode===mode&&x.locale===locale&&x.ownerId===p.ownerId,'mode_locale_owner');require(x.format==='legacy_source'&&x.sourcePayload&&hash(x.sourcePayload)===x.sourcePayloadHash,'legacy_source_hash');require(inheritedBaselineHashes[p.ownerId+'.'+mode+'.'+locale]===x.sourcePayloadHash&&inheritedBaselineHashes[p.ownerId+'.'+mode+'.'+locale+'.projection']===hash(x),'unproven_legacy_baseline');require(Array.isArray(x.references),'legacy_reference_shape');const state=r.referenceState?.[mode]?.[locale];require(['present','legacy_missing','legacy_locale_divergence'].includes(state),'legacy_reference_state');require(x.references.length>0||state==='legacy_missing','legacy_reference_missing');if(state==='legacy_missing')require(x.references.length===0,'legacy_reference_state_mismatch');if(mode==='study'){require(x.sourcePayload.id===p.ownerId&&x.sourcePayload.title?.[locale]&&x.sourcePayload.actions?.[locale],'legacy_protocol_binding');const model=rows.clinical_legacy_protocols.find(a=>a.canonicalPathologyKey===p.ownerId);require(model&&canonical(model.payload)===canonical(x.sourcePayload),'legacy_protocol_source_binding');}else{require(typeof x.sourcePayload.providerPrompt==='string'&&x.sourcePayload.providerPrompt.length,'legacy_context_missing');}}require(count>0,'owner_has_no_projection');}
 const meta=projectionMetadata(rows);for(const k of Object.keys(meta))require(canonical(m[k])===canonical(meta[k]),'manifest_surface_metadata');require(hash([...owners].sort())===m.ownerSetHash,'owner_set_hash');return {OWNER_COUNT:owners.size,SCHEMA:'PASS',HASHES:'PASS',FUNCTIONAL_PARITY:'PASS',...Object.fromEntries(['studyPtCount','studyEsCount','plantaoPtCount','plantaoEsCount'].map(k=>[k,m[k]]))};}
