import {projectionForSchema} from './phase3_projection.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {collections,prepare,hash,canonical} from './publication.mjs';import {textHash} from './phase2_adapter.mjs';import {slots,resolveOwner} from './phase3_resolver.mjs';
const [work]=process.argv.slice(2);assert.ok(work);const r2=work+'/r2',out=work+'/out';fs.mkdirSync(out,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p)),save=(f,v)=>fs.writeFileSync(out+'/'+f,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n',{mode:0o600});
const baseline=read(r2+'/R2-B.json'),baselineManifest=read(r2+'/PHASE2_TARGET_MANIFEST.json'),input=read(r2+'/PHASE2_OWNER_CLASSIFICATION.json').filter(r=>!r.RESOLVED);assert.equal(input.length,342);assert.equal(baseline.manifest.ownerCount,235);assert.equal(baselineManifest.ownerCount,235);
const frozen=new Set(baselineManifest.owners.map(r=>r.owner)),hold=new Set(input.map(r=>r.OWNER_ID));assert.equal([...hold].filter(o=>frozen.has(o)).length,0);
const source=read(work+'/r1/source-export.json'),remote=read('/private/tmp/medcases-r3-remote-content-all.json'),candidates=read('/private/tmp/medcases-r3-candidates.json');
const local=read('/private/tmp/medcases-r3-local-catalog.json'),localById=new Map(local.map(r=>[r.id,r]));const auditMatches=read(out+'/PHASE3_AUDIT_OWNER_MATCHES.json');
const frozenRows=Object.fromEntries(collections.map(c=>[c,baseline.manifest.chunks.filter(d=>d.collection===c).flatMap(d=>JSON.parse(baseline.chunks[d.id].json))]));
const targetRows=structuredClone(frozenRows),records=[],provenance=[],hashes=[],resolved=[];
const sourceFingerprints=Object.fromEntries(['R2-B.json','PHASE2_TARGET_MANIFEST.json','PHASE2_OWNER_CLASSIFICATION.json'].map(f=>[f,textHash(fs.readFileSync(r2+'/'+f))]));
for(const row of input){
 const owner=row.OWNER_ID,cs=candidates.filter(c=>c.owner===owner),result=resolveOwner(owner,cs);
 const localEvidence=localById.get(owner),remoteEvidence=remote.filter(r=>r.canonicalPathologyKey===owner);
 const record={OWNER_ID:owner,CURRENT_STATUS:'HOLD',RECOVERY_CLASS:result.classification,STUDY_PT_SOURCE:null,STUDY_ES_SOURCE:null,PLANTAO_PT_SOURCE:null,PLANTAO_ES_SOURCE:null,REFERENCES_SOURCE:null,PROVENANCE_COMPLETE:result.recovered?'YES':'NO',HASH_STATUS:result.recovered?'PASS':'APPROVED_PROJECTION_HASH_UNPROVEN',VERSION_COMPATIBLE:result.recovered?'YES':'UNVERIFIED',RECOVERED:result.recovered?'YES':'NO',BLOCK_REASON:result.recovered?[]:result.reasons.length?result.reasons:['MISSING_APPROVAL_FOR_FOUR_EXPLICIT_PROJECTIONS'],LOCAL_EXACT_ID_PRESENT:!!localEvidence,LOCAL_SOURCE:localEvidence??null,REMOTE_SOURCE_DOCUMENTS:remoteEvidence.map(r=>({id:r.id,version:r.version,enabled:r.enabled,sha256:hash(r)})),AUDIT_EVIDENCE_PATHS:auditMatches[owner]??[]};
 if(result.recovered){
  const c=result.selected,raw=remote.find(r=>r.id===c.sourceDocumentId);assert.ok(raw);assert.equal(hash(raw),c.sourceHash);
  const identity=source.clinical_identity_registry.find(r=>r.canonicalKey===owner);assert.ok(identity);targetRows.clinical_identity_registry.push(structuredClone(identity));
  // New versioned projection record; source document and its enabled=false are
  // untouched. No old machine actions are mixed with recovered clinical text.
  const targetPayload=structuredClone(raw.payload);
  for(const slot of slots){const [mode,locale]=slot.split('_');targetPayload[locale][mode+'Projection']=projectionForSchema(raw.payload[locale][mode+'Projection']);}
  targetRows.clinical_content_registry.push({id:'r3_recovered::'+owner,canonicalPathologyKey:owner,version:raw.version,approvedClinicalPayloadSha256:raw.approvedClinicalPayloadSha256,payload:targetPayload,recoveryEvidence:{sourceDocumentId:raw.id,sourceEnabled:raw.enabled,sourceSha256:c.sourceHash,approvalEvidence:c.approvalEvidence}});
  for(const slot of slots){const [mode,locale]=slot.split('_'),p=c.projections[slot],pr={OWNER_ID:owner,MODE:mode.toUpperCase(),LOCALE:locale.toUpperCase(),SOURCE_TYPE:c.sourceType,SOURCE_PATH:c.sourcePath+'#'+raw.id+'/payload/'+locale+'/'+mode+'Projection',SOURCE_DOCUMENT_ID:raw.id,SOURCE_VERSION:c.version,SOURCE_HASH:c.sourceHash,APPROVAL_EVIDENCE:c.approvalEvidence,APPROVAL_STATUS:'PASS',RECOVERY_METHOD:'REFERENCE_ID_NUMBER_TO_STRING_ONLY',SOURCE_PROJECTION_HASH:p.sourceHash,TARGET_PROJECTION_HASH:hash(targetPayload[locale][mode+'Projection']),HASH_PRESERVED:'NO_STRUCTURAL_ONLY',CLINICAL_BYTES_PRESERVED:true,SOURCE_REFERENCE_HASH:hash(p.references),REFERENCE_HASH:hash(targetPayload[locale][mode+'Projection'].references)};provenance.push(pr);record[slot.toUpperCase()+'_SOURCE']=pr.SOURCE_PATH;hashes.push(pr);}
  record.REFERENCES_SOURCE=c.sourcePath+'#'+raw.id+'/payload';resolved.push(owner);
 }
 records.push(record);
}
assert.equal(new Set(records.map(r=>r.OWNER_ID)).size,342);
// Compare every frozen row, not just the owner counts or four projection hashes.
for(const c of collections)assert.equal(canonical(targetRows[c].slice(0,frozenRows[c].length)),canonical(frozenRows[c]));
const a=prepare('R2-A',frozenRows),b=prepare('R3-B',targetRows);save('R3-A.json',a);save('R3-B.json',b);save('R2-B-frozen.json',fs.readFileSync(r2+'/R2-B.json','utf8'));
save('PHASE3_BASELINE_MANIFEST.json',baselineManifest.owners.map(r=>({OWNER_ID:r.owner,SOURCE_DOCS:[r.source],...Object.fromEntries(Object.entries(r.projectionHashes).map(([k,v])=>[k.toUpperCase()+'_HASH',v])),REFERENCE_HASH:r.referencesHash,STATUS:'FROZEN_VALID_R2'})));
save('PHASE3_OWNER_RECOVERY.json',records);save('PHASE3_PROVENANCE_MANIFEST.json',provenance);save('PHASE3_HASH_AUDIT.json',{baselineSourceFiles:sourceFingerprints,baselineRowsUnchanged:true,recoveredProjections:hashes,clinicalContentChanged:0});
const cols=['OWNER_ID','CURRENT_STATUS','RECOVERY_CLASS','STUDY_PT_SOURCE','STUDY_ES_SOURCE','PLANTAO_PT_SOURCE','PLANTAO_ES_SOURCE','REFERENCES_SOURCE','PROVENANCE_COMPLETE','HASH_STATUS','VERSION_COMPATIBLE','RECOVERED','BLOCK_REASON'];save('PHASE3_OWNER_RECOVERY.csv',cols.join(',')+'\n'+records.map(r=>cols.map(k=>'"'+(Array.isArray(r[k])?r[k].join(';'):String(r[k]??'')).replaceAll('"','""')+'"').join(',')).join('\n')+'\n');
for(const [name,group] of [['APPROVED_REMOTE_RECOVERY','A'],['APPROVED_HISTORICAL_RECOVERY','B'],['APPROVED_LOCAL_RECOVERY','C'],['CROSS_SOURCE_RECOVERY','D'],['TRUE_CLINICAL_GAPS','E'],['UNRESOLVED_PROVENANCE','F'],['CONFLICTING_APPROVED_SOURCES','G']])save(`PHASE3_${name}.md`,`# ${name}\n\n`+records.filter(r=>r.RECOVERY_CLASS.startsWith(group+'_')).map(r=>`- ${r.OWNER_ID}: ${r.RECOVERED==='YES'?'RECOVERED — approval/hash/identity/version PASS':r.BLOCK_REASON.join(', ')}; local exact ID: ${r.LOCAL_EXACT_ID_PRESENT}.`).join('\n')+'\n');
const classes=['A_APPROVED_REMOTE_RECOVERY','B_APPROVED_HISTORICAL_RECOVERY','C_APPROVED_LOCAL_RECOVERY','D_APPROVED_CROSS_SOURCE_RECOVERY','E_TRUE_CLINICAL_GAP','F_UNRESOLVED_PROVENANCE','G_CONFLICTING_APPROVED_SOURCES'];
const metrics={PHASE:'REMOTE_CONTENT_MIGRATION_R3',FROZEN_VALID_INPUT:235,HOLD_INPUT:342,...Object.fromEntries(classes.map(c=>[c,records.filter(r=>r.RECOVERY_CLASS===c).length])),TOTAL_RECOVERED_PHASE3:resolved.length,TOTAL_COMPLETE_AFTER_PHASE3:235+resolved.length,TOTAL_PENDING_AFTER_PHASE3:342-resolved.length,...Object.fromEntries(slots.map(s=>[s.toUpperCase()+'_RECOVERED',resolved.length])),PROVENANCE_COMPLETE_COUNT:resolved.length,HASH_PRESERVED_COUNT:0,CLINICAL_BYTES_PRESERVED_COUNT:provenance.length,STRUCTURAL_ONLY_PROJECTION_COUNT:provenance.length,HASH_CONFLICT_COUNT:candidates.filter(c=>hold.has(c.owner)&&c.hashStatus==='FAIL').length,REFERENCE_GATE:'PASS_RECOVERED_TARGET',CURRENT_PRODUCTION_OWNER_COVERAGE:577,REMOTE_TARGET_OWNER_COVERAGE:235+resolved.length,COVERAGE_PERCENT:100*(235+resolved.length)/577,COVERAGE_GATE:235+resolved.length===577?'PASS':'FAIL',CLINICAL_CONTENT_CREATED:0,CLINICAL_CONTENT_TRANSLATED:0,CLINICAL_CONTENT_REWRITTEN:0,PRODUCTION_WRITES:0,DEPLOY:'NO',COMMIT:'NO',PUSH:'NO',REMOTE_CONTENT_MIGRATION_READY:'NO',PRODUCTION_ACTIVATION_READY:'NO'};
save('PHASE3_METRICS.json',metrics);save('PHASE3_TARGET_MANIFEST.json',{status:'DRAFT_LOCAL_ONLY',baselineOwners:235,recoveredOwners:resolved,ownerCount:b.manifest.ownerCount,manifest:b.manifest,baselineSHA256:sourceFingerprints['R2-B.json'],targetFileSHA256:textHash(fs.readFileSync(out+'/R3-B.json')),sourceEnabledMutation:false,machineRuleRecovery:'NOT_INFERRED_OR_MIXED; baseline machine rows preserved; new owners are projection-only',productionActivation:'NO'});
save('PHASE3_COVERAGE_REPORT.md',`# Coverage R3\n\n${235+resolved.length}/577 (${metrics.COVERAGE_PERCENT.toFixed(2)}%). ${342-resolved.length} HOLD. Coverage FAIL; nenhuma ativação parcial. Baseline R2 preservado.\n`);
for(const [f,h] of Object.entries(sourceFingerprints))assert.equal(textHash(fs.readFileSync(r2+'/'+f)),h);
console.log(JSON.stringify(metrics,null,2));
