import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {canonical,hash,collections,prepare} from './publication.mjs';
import {normalizeLegacyContent} from './legacy_projection_adapter.mjs';
import {normalizePhase2,fingerprint,mappings,textHash} from './phase2_adapter.mjs';
const [sourceFile,out]=process.argv.slice(2);if(!sourceFile||!out)throw Error('SOURCE OUTPUT required');
const bytes=fs.readFileSync(sourceFile),source=JSON.parse(bytes);fs.mkdirSync(out,{recursive:true});
const save=(f,v)=>fs.writeFileSync(path.join(out,f),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n',{mode:0o600});
const docs=source.clinical_content_registry, original=docs.map(normalizeLegacyContent),normalized=docs.map(normalizePhase2);
const frozen=original.filter(n=>n.status==='RESOLVED');assert.equal(frozen.length,219);
const frozenOwners=new Set(frozen.map(n=>n.owner));
const projectionHashes=n=>Object.fromEntries(['study','plantao'].flatMap(m=>['pt','es'].map(l=>[`${m}_${l}`,n[m][l]?textHash(n[m][l].value):null])));
const baseline=frozen.map(n=>({OWNER_ID:n.owner,SOURCE_DOCS:docs.filter(r=>r.canonicalPathologyKey===n.owner).map(r=>r.id),SOURCE_SHAPE:docs.filter(r=>r.canonicalPathologyKey===n.owner).map(fingerprint),PROJECTION_HASH:projectionHashes(n),...Object.fromEntries(Object.entries(projectionHashes(n)).map(([k,v])=>[k.toUpperCase()+'_HASH',v])),REFERENCES_HASH:hash(n.references),SOURCE_HASH:n.metadata.sourceSha256,NORMALIZED_HASH:hash(n),APPROVED_HASH:n.metadata.approvedClinicalPayloadSha256,STATUS:'FROZEN_VALID'}));
for(const n of frozen)assert.equal(canonical(normalized.find(x=>x.metadata.sourceId===n.metadata.sourceId)),canonical(n));
const classifications=[],relations=[],hashAudit=[],selected=[...frozen];
for(const identity of [...source.clinical_identity_registry].sort((a,b)=>a.canonicalKey.localeCompare(b.canonicalKey))){
 const owner=identity.canonicalKey,raws=docs.filter(r=>r.canonicalPathologyKey===owner),ns=normalized.filter(n=>n.owner===owner);
 const conflicts=ns.flatMap(n=>n.metadata.conflicts), reasons=[];
 const projections={};let present=0;
 for(const m of ['study','plantao'])for(const l of ['pt','es']){const candidates=ns.filter(n=>n[m][l]);const state=candidates.length>1?'CONFLICT':candidates.length===1?'PRESENT':'MISSING';projections[`${m}_${l}`]=state;if(state==='PRESENT')present++;if(state==='CONFLICT')conflicts.push(`MULTIPLE_${m}_${l}_CANDIDATES`);if(state==='MISSING')reasons.push(`MISSING_${m}_${l}`.toUpperCase());}
 if(ns.some(n=>n.metadata.approvedHashStatus==='FAIL'))conflicts.push('HASH_CONFLICT');
 // Different versions of supplemental classifications are retained as evidence,
 // not treated as competing primary projections without an explicit shared contract.
 const roles=raws.map((r,i)=>({id:r.id,role:r.contentKey?.startsWith('legacy_classification_content::')?'SUPPLEMENTAL_CLASSIFICATION':'PROTOCOL',version:r.version,enabled:r.enabled,sourceMode:r.sourceMode,shape:fingerprint(r),localePaths:Object.keys(r.payload??{}).filter(k=>['pt','es','locales'].includes(k)),projectionPaths:ns[i]?.metadata.sourcePaths,referenceHash:hash(ns[i]?.references??null),sourceHash:hash(r),historical:'UNPROVEN',aliases:identity.aliases??identity.strongAliases??null}));
 relations.push({owner,relation:raws.length===1?'1:1':'1:N',documents:roles,mixedDocumentVersions:new Set(raws.map(r=>r.version)).size>1,policy:'DO_NOT_CONFLATE_SUPPLEMENTAL_WITH_PRIMARY'});
 const valid=ns.filter(n=>n.status==='RESOLVED');
 let category=conflicts.length?'D_TECHNICAL_CONFLICT':present===4?'A_STRUCTURAL_RESOLVABLE':present?'B_PARTIAL_CONTENT':'C_AMBIGUOUS_OR_MISSING';
 if(present===4&&!conflicts.length&&valid.length!==1){category='D_TECHNICAL_CONFLICT';conflicts.push('FOUR_PROJECTIONS_WITHOUT_VALID_APPROVAL_OR_REFERENCES');}
 const aliasResolved=valid.length===1&&valid[0].metadata.nonclinicalResolution==='APPROVED_PRESERVED_RUNTIME_ID'&&!conflicts.length;
 if(aliasResolved)category='D_TECHNICAL_CONFLICT';
 const row={OWNER_ID:owner,SOURCE_DOCUMENTS:raws.map(r=>r.id),SOURCE_SHAPES:raws.map(fingerprint),RELATION:raws.length===1?'1:1':'1:N',...Object.fromEntries(Object.entries(projections).map(([k,v])=>[k.toUpperCase(),v])),REFERENCES:ns.map(n=>({source:n.metadata.sourceId,present:Array.isArray(n.references)&&n.references.length>0,sha256:hash(n.references)})),HASH_STATUS:ns.map(n=>({source:n.metadata.sourceId,status:n.metadata.approvedHashStatus})),LOCALE_STATUS:present===4?'EXPLICIT_PT_ES':'UNSCOPED_OR_MISSING',CONFLICT_STATUS:conflicts.length?'CONFLICT':'NONE',CLASSIFICATION:category,REASON:[...conflicts,...reasons,...(aliasResolved?['RESOLVED_APPROVED_PRESERVED_RUNTIME_ID']:[])],RESOLVED:(category==='A_STRUCTURAL_RESOLVABLE'||aliasResolved)&&valid.length===1};
 if(!frozenOwners.has(owner)){classifications.push(row);if(row.RESOLVED)selected.push(valid[0]);}
 for(const n of ns)hashAudit.push({OWNER_ID:owner,SOURCE_ID:n.metadata.sourceId,SOURCE_HASH:n.metadata.sourceSha256,NORMALIZED_HASH:hash(n),PROJECTION_HASH:projectionHashes(n),REFERENCES_HASH:hash(n.references),APPROVED_HASH:n.metadata.approvedClinicalPayloadSha256,APPROVED_HASH_STATUS:n.metadata.approvedHashStatus,HASH_PRESERVED:'YES',CONFLICTS:n.metadata.conflicts});
}
assert.equal(classifications.length,358);assert.equal(relations.length,577);assert.equal(relations.filter(r=>r.relation==='1:N').length,94);
const count=c=>classifications.filter(r=>r.CLASSIFICATION===c).length;
const metrics={FROZEN_VALID_OWNERS:219,PENDING_INPUT:358,A_STRUCTURAL_RESOLVABLE:count('A_STRUCTURAL_RESOLVABLE'),A_RESOLVED:classifications.filter(r=>r.RESOLVED&&r.CLASSIFICATION==='A_STRUCTURAL_RESOLVABLE').length,B_PARTIAL_CONTENT:count('B_PARTIAL_CONTENT'),C_AMBIGUOUS_OR_MISSING:count('C_AMBIGUOUS_OR_MISSING'),D_TECHNICAL_CONFLICT:count('D_TECHNICAL_CONFLICT'),D_RESOLVED_NONCLINICAL:classifications.filter(r=>r.RESOLVED&&r.CLASSIFICATION==='D_TECHNICAL_CONFLICT').length,TOTAL_COMPLETE_AFTER_PHASE2:selected.length,TOTAL_PENDING_AFTER_PHASE2:577-selected.length,ONE_TO_ONE_RESOLVED:classifications.filter(r=>r.RESOLVED&&r.RELATION==='1:1').length,ONE_TO_MANY_RESOLVED:classifications.filter(r=>r.RESOLVED&&r.RELATION==='1:N').length,SHAPES_SUPPORTED:`${mappings.length}/37`,SHAPE_SUPPORT_MEANING:'EXPLICIT_MAPPING_OR_DETERMINISTIC_HOLD',PT_ES_PARITY_COMPLETE:selected.length,STUDY_PLANTAO_PARITY_COMPLETE:selected.length,HASH_PRESERVED_COUNT:hashAudit.length,HASH_VERIFIED_APPROVED_COUNT:hashAudit.filter(r=>r.APPROVED_HASH_STATUS==='PASS').length,HASH_CONFLICT_COUNT:hashAudit.filter(r=>r.APPROVED_HASH_STATUS==='FAIL').length,REFERENCE_GATE:'PASS_TARGET_ONLY',CURRENT_PRODUCTION_OWNER_COVERAGE:577,REMOTE_TARGET_OWNER_COVERAGE:selected.length,COVERAGE_PERCENT:100*selected.length/577,COVERAGE_GATE:selected.length===577?'PASS':'FAIL',PRODUCTION_WRITES:0,DEPLOY:'NO',COMMIT:'NO',PUSH:'NO',REMOTE_CONTENT_MIGRATION_READY:'NO',PRODUCTION_ACTIVATION_READY:'NO',SOURCE_SHA256:textHash(bytes),SOURCE_MUTATED:'NO'};
save('PHASE2_BASELINE_MANIFEST.json',baseline);save('PHASE2_OWNER_CLASSIFICATION.json',classifications);save('PHASE2_RELATION_AUDIT.json',relations);save('PHASE2_SHAPE_MAPPING.json',mappings);save('PHASE2_HASH_AUDIT.json',hashAudit);save('PHASE2_METRICS.json',metrics);
const cols=Object.keys(classifications[0]);save('PHASE2_OWNER_CLASSIFICATION.csv',cols.join(',')+'\n'+classifications.map(r=>cols.map(k=>'"'+(typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k])).replaceAll('"','""')+'"').join(',')).join('\n')+'\n');
for(const [name,c] of [['B_PARTIAL','B_PARTIAL_CONTENT'],['C_AMBIGUOUS','C_AMBIGUOUS_OR_MISSING'],['D_CONFLICTS','D_TECHNICAL_CONFLICT']])save(`PHASE2_HOLD_${name}.md`,`# ${c}\n\n`+classifications.filter(r=>r.CLASSIFICATION===c&&!r.RESOLVED).map(r=>`- ${r.OWNER_ID}: ${r.REASON.join(', ')}; fontes: ${r.SOURCE_DOCUMENTS.join(', ')}.`).join('\n')+'\n');
save('PHASE2_DRY_RUN.json',{status:'DRAFT_LOCAL_ONLY',frozen:baseline.map(x=>x.OWNER_ID),create:classifications.filter(r=>r.RESOLVED).map(r=>r.OWNER_ID),hold:classifications.filter(r=>!r.RESOLVED).map(r=>({owner:r.OWNER_ID,reasons:r.REASON})),productionWrites:0});
save('PHASE2_NORMALIZED_TARGET.json',selected);
save('PHASE2_TARGET_MANIFEST.json',{status:'DRAFT',schemaVersion:1,ownerCount:selected.length,normalizedSha256:hash(selected),owners:selected.map(n=>({owner:n.owner,source:n.metadata.sourceId,sourceHash:n.metadata.sourceSha256,projectionHashes:projectionHashes(n),referencesHash:hash(n.references)})),supplementalPolicy:'Original documents preserved in immutable source export; not promoted as independent four-mode projections',activationBlocked:metrics.COVERAGE_GATE!=='PASS'});
save('PHASE2_COVERAGE_REPORT.md',`# Coverage\n\nFonte: export de produção da fase 1, SHA-256 ${metrics.SOURCE_SHA256}. Não é uma nova leitura de produção.\n\nProdução: 577 owners enabled. Alvo completo: ${selected.length} (${metrics.COVERAGE_PERCENT.toFixed(2)}%). HOLD: ${577-selected.length}. COVERAGE_GATE=FAIL. Nenhuma ativação parcial autorizada.\n`);
save('PHASE2_STRUCTURAL_RESOLUTION_REPORT.md',`# Resolução estrutural R2\n\n219 normalizações congeladas byte a byte. ${metrics.A_RESOLVED} owners A e ${metrics.D_RESOLVED_NONCLINICAL} conflitos D com vínculo explícito preservedRuntimeIds no JSON aprovado; owners adicionais resolvidos lendo JSON serializado aprovado em payload.approvedClinicalPayload, com hash SHA-256, owner e versão conferidos. Nenhuma tradução ou cópia entre modos.\n\n37 formatos possuem política explícita, inclusive HOLD. Suporte de shape não significa conteúdo completo. Os campos genéricos actions, summary e locales não provam uma projeção de Estudo ou Plantão. Referências e documentos suplementares permanecem preservados no export original. Divergência de versões entre documento primário e classificação suplementar é registrada, sem presumir histórico ou conflito de projeção.\n\nAs 358 classificações e 94 relações 1:N estão nos arquivos JSON/CSV. SHA-256 aprovado é preservado; hash de normalização é separado e não substitui o hash da fonte.\n`);
assert.equal(textHash(fs.readFileSync(sourceFile)),metrics.SOURCE_SHA256);
console.log(JSON.stringify(metrics,null,2));
